const CATEGORIES = [
  { label: "Women’s Clothing", param: "women-clothing", value: "women clothing" },
  { label: "Hats and Caps", param: "clothing", value: "hats and caps" },
  { label: "Sweaters", param: "clothing", value: "sweaters" },
  { label: "Jeans", param: "clothing", value: "jeans" },
  { label: "Shorts", param: "clothing", value: "shorts" },
  { label: "Men’s Clothing", param: "men-clothing", value: "men's clothing" },
  { label: "Phones & Accessories", param: "phones", value: "phones" },
  { label: "Phones [One SIM]", param: "phones", value: "single SIM card" },
  { label: "Phones [Two SIM]", param: "phones", value: "dual SIM card" },
  { label: "Mobile Phone Accessories", param: "phones", value: "mobile phone accessories" },
  { label: "Electronics", param: "electronics", value: "electronics" },
  { label: "Computers", param: "computers", value: "computers" },
  { label: "Laptops", param: "computers", value: "laptops" },
  { label: "Laptops", param: "computers", value: "gaming laptops" },
  { label: "Watches", param: "watches", value: "watches" },
  { label: "Snickers", param: "snickers", value: "snickers" },
  { label: "Beads & DIY Jewelry", param: "beads", value: "beads" },
  { label: "Printers", param: "printers", value: "printers" },
  { label: "Tablets", param: "tablets", value: "tablets" },
  { label: "Tablets", param: "scanners", value: "scanners" },
  { label: "Wireless Routers", param: "routers", value: "routers" },
  { label: "Men's Bags", param: "men-bags", value: "men's bags" },
  { label: "Women's Bags", param: "women-bags", value: "women's bags" },
  { label: "Wallets", param: "wallets", value: "wallets" },
  { label: "Women's Shoes", param: "women-shoe", value: "women's shoes" },
  { label: "Men's Shoes", param: "men-shoe", value: "men's shoes" },
  { label: "Briefcases", param: "briefcase", value: "briefcases" },
  { label: "Bags & Shoes", param: "bags-shoes", value: "Bags & Shoes" },
  { label: "Toys", param: "toys", value: "toys" },
  { label: "Baby Clothings", param: "baby-clothings", value: "baby clothings" },
  { label: "Baby Care", param: "baby-care", value: "baby care" },
  { label: "Maternity", param: "maternity", value: "maternity" },
  { label: "E-Books", param: "e-books", value: "e-books" },
  { label: "Audio Books", param: "audio-books", value: "audio books" },
  { label: "Photography", param: "photography", value: "photography" },
  { label: "Blueprints", param: "blueprints", value: "blueprints" },
  { label: "Music Albums", param: "music-albums", value: "music albums" },
  { label: "Music", param: "music", value: "music" },
  { label: "Others", param: "others", value: "others" }
];
export default CATEGORIES;
